import { chromium } from 'playwright';
const B='http://localhost:8901/for/associates.html';
const OUT=process.argv[2];
const browser=await chromium.launch();
const pg=await browser.newPage({viewport:{width:1440,height:1000}});
await pg.goto(B,{waitUntil:'networkidle'});
await pg.screenshot({path:OUT+'/door-1440-top.png'});
await pg.fill('#lgTotal','1284');await pg.fill('#lgDirect','742');
await pg.fill('#lgRel','228');await pg.fill('#lgWeeks','61');await pg.fill('#lgRate','18');
await pg.waitForTimeout(300);
await pg.locator('#ledger').scrollIntoViewIfNeeded();
await pg.screenshot({path:OUT+'/door-1440-ledger.png'});
await pg.locator('#asking').scrollIntoViewIfNeeded();
await pg.screenshot({path:OUT+'/door-1440-asking.png'});
await pg.locator('#shelf').scrollIntoViewIfNeeded();
await pg.screenshot({path:OUT+'/door-1440-shelf.png'});
await pg.close();
const m=await browser.newPage({viewport:{width:375,height:812}});
await m.goto(B,{waitUntil:'networkidle'});
await m.screenshot({path:OUT+'/door-375-top.png'});
await m.locator('#ledger').scrollIntoViewIfNeeded();
await m.screenshot({path:OUT+'/door-375-ledger.png'});
await browser.close();
