#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""California health center organizations. WRITTEN BY _dev/hc_orgs.py.

Do not edit by hand - rerun the ETL, which needs network because it fetches
every candidate domain before writing it as a link.

`url` is None where the address in the federal file did not answer an
automated request. That is NOT the same as the organization having no
website - several are behind bot protection - so those rows ship as plain
text. A wrong link is worse than no link.
"""

CHECKED = '11 August 2026'

ORGS = [
    {'name': '3C Community Clinic', 'raw': '3C COMMUNITY CLINIC', 'sites': 2, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://3cclinic.org'},
    {'name': 'AAA Comprehensive Healthcare Inc.', 'raw': 'AAA COMPREHENSIVE HEALTHCARE INC.', 'sites': 3, 'counties': ['Los Angeles', 'Orange'], 'lookalike': False, 'city': 'North Hollywood', 'url': None},
    {'name': 'Access Community Health Center', 'raw': 'ACCESS COMMUNITY HEALTH CENTER', 'sites': 3, 'counties': ['Orange'], 'lookalike': True, 'city': 'Santa Ana', 'url': 'https://accessfqhc.org'},
    {'name': 'Aghaby Comprehensive Community Health Center', 'raw': 'AGHABY COMPREHENSIVE COMMUNITY HEALTH CENTER', 'sites': 1, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Compton', 'url': None},
    {'name': 'AIDS Services Foundation Orange County', 'raw': 'AIDS SERVICES FOUNDATION ORANGE COUNTY', 'sites': 1, 'counties': ['Orange'], 'lookalike': True, 'city': 'Irvine', 'url': 'https://radianthealthcenters.org'},
    {'name': 'County of Alameda', 'raw': 'ALAMEDA, COUNTY OF', 'sites': 28, 'counties': ['Alameda'], 'lookalike': False, 'city': 'Oakland', 'url': 'https://achch.org'},
    {'name': 'All for Health, Health for All, Inc.', 'raw': 'ALL FOR HEALTH, HEALTH FOR ALL, INC.', 'sites': 15, 'counties': ['Los Angeles', 'Orange'], 'lookalike': False, 'city': 'Glendale', 'url': 'https://all4health.org'},
    {'name': 'All-inclusive Community Health Center', 'raw': 'ALL-INCLUSIVE COMMUNITY HEALTH CENTER', 'sites': 5, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Burbank', 'url': 'https://aichc.org'},
    {'name': 'Alliance Medical Center, Inc.', 'raw': 'ALLIANCE MEDICAL CENTER, INC', 'sites': 8, 'counties': ['Sonoma'], 'lookalike': False, 'city': 'Windsor', 'url': 'https://alliancemed.org'},
    {'name': 'Altamed Health Services Corporation', 'raw': 'ALTAMED HEALTH SERVICES CORPORATION', 'sites': 133, 'counties': ['Los Angeles', 'Orange'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://altamed.org'},
    {'name': 'Altura Centers for Health', 'raw': 'ALTURA CENTERS FOR HEALTH', 'sites': 9, 'counties': ['Tulare'], 'lookalike': False, 'city': 'Tulare', 'url': 'https://altura.org'},
    {'name': 'AMH Comprehensive Medical Centers', 'raw': 'AMH COMPREHENSIVE MEDICAL CENTERS', 'sites': 5, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Maywood', 'url': None},
    {'name': 'Ampla Health', 'raw': 'AMPLA HEALTH', 'sites': 24, 'counties': ['Butte', 'Colusa', 'Glenn', 'Sutter', 'Tehama', 'Yuba'], 'lookalike': False, 'city': 'Yuba City', 'url': 'https://amplahealth.org'},
    {'name': 'Anderson Valley Health Center Inc.', 'raw': 'ANDERSON VALLEY HEALTH CENTER INC', 'sites': 1, 'counties': ['Mendocino'], 'lookalike': False, 'city': 'Boonville', 'url': 'https://avhc.org'},
    {'name': 'Anphon Corporation', 'raw': 'ANPHON CORPORATION', 'sites': 2, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Inglewood', 'url': 'https://amchealthcare.org'},
    {'name': 'Apla Health & Wellness', 'raw': 'APLA HEALTH & WELLNESS', 'sites': 14, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://apla.org'},
    {'name': 'Arroyo Vista Family Health Foundation', 'raw': 'ARROYO VISTA FAMILY HEALTH FOUNDATION', 'sites': 5, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://arroyovista.org'},
    {'name': 'Asian and Pacific Islander Wellness Center, Inc.', 'raw': 'ASIAN AND PACIFIC ISLANDER WELLNESS CENTER, INC.', 'sites': 5, 'counties': ['San Francisco'], 'lookalike': False, 'city': 'San Francisco', 'url': 'https://sfcommunityhealth.org'},
    {'name': 'Asian Health Services', 'raw': 'ASIAN HEALTH SERVICES', 'sites': 16, 'counties': ['Alameda'], 'lookalike': False, 'city': 'Oakland', 'url': 'https://asianhealthservices.org'},
    {'name': 'Asian Pacific Health Care Venture, Inc.', 'raw': 'ASIAN PACIFIC HEALTH CARE VENTURE, INC.', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://aphcv.org'},
    {'name': 'Axis Community Health, Inc.', 'raw': 'AXIS COMMUNITY HEALTH, INC.', 'sites': 6, 'counties': ['Alameda'], 'lookalike': False, 'city': 'Livermore', 'url': 'https://axishealth.org'},
    {'name': 'American Indian Health & Services Corporation', 'raw': 'American Indian Health & Services Corporation', 'sites': 3, 'counties': ['Santa Barbara'], 'lookalike': False, 'city': 'Santa Barbara', 'url': 'https://aihscorp.org'},
    {'name': 'Aria Community Health Center', 'raw': 'Aria Community Health Center', 'sites': 36, 'counties': ['Fresno', 'Kings', 'Tulare'], 'lookalike': False, 'city': 'Lindsay', 'url': 'https://ariachc.org'},
    {'name': 'Bartz-altadonna Community Health Center', 'raw': 'BARTZ-ALTADONNA COMMUNITY HEALTH CENTER', 'sites': 11, 'counties': ['Kern', 'Los Angeles'], 'lookalike': False, 'city': 'Lancaster', 'url': None},
    {'name': 'Bay Area Community Health', 'raw': 'BAY AREA COMMUNITY HEALTH', 'sites': 39, 'counties': ['Alameda', 'Santa Clara'], 'lookalike': False, 'city': 'Fremont', 'url': 'https://bach.health'},
    {'name': 'Behavioral Health Services, Inc.', 'raw': 'BEHAVIORAL HEALTH SERVICES, INC.', 'sites': 9, 'counties': ['Los Angeles', 'Orange'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://bhs-inc.org'},
    {'name': 'Benevolence Industries Inc.', 'raw': 'BENEVOLENCE INDUSTRIES INC', 'sites': 10, 'counties': ['Los Angeles', 'Orange'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://bhchealth.org'},
    {'name': 'Beverly Community Clinic', 'raw': 'BEVERLY COMMUNITY CLINIC', 'sites': 3, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://beverlycommunityclinic.com'},
    {'name': 'Beverlycare', 'raw': 'BEVERLYCARE', 'sites': 7, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Montebello', 'url': 'https://beverlycare.org'},
    {'name': 'Bienestar Human Services, Inc.', 'raw': 'BIENESTAR HUMAN SERVICES, INC', 'sites': 1, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://bienestar.org'},
    {'name': 'Blessing Community Health Center', 'raw': 'BLESSING COMMUNITY HEALTH CENTER', 'sites': 1, 'counties': ['San Bernardino'], 'lookalike': True, 'city': 'San Bernardino', 'url': 'https://blessingchc.com'},
    {'name': 'Brighter Beginnings', 'raw': 'BRIGHTER BEGINNINGS', 'sites': 5, 'counties': ['Alameda', 'Contra Costa'], 'lookalike': True, 'city': 'Antioch', 'url': 'https://brighter-beginnings.org'},
    {'name': 'Buddhist Tzu Chi Medical Foundation', 'raw': 'BUDDHIST TZU CHI MEDICAL FOUNDATION', 'sites': 7, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'South El Monte', 'url': 'https://tzuchimedical.us'},
    {'name': 'Cali Med Corporation', 'raw': 'CALI MED CORPORATION', 'sites': 8, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Downey', 'url': 'https://calimedhealth.org'},
    {'name': 'Camarena Health', 'raw': 'CAMARENA HEALTH', 'sites': 28, 'counties': ['Fresno', 'Madera', 'Mariposa', 'Merced'], 'lookalike': False, 'city': 'Madera', 'url': 'https://camarenahealth.org'},
    {'name': 'Camino Health Center', 'raw': 'CAMINO HEALTH CENTER', 'sites': 5, 'counties': ['Orange'], 'lookalike': False, 'city': 'San Juan Capistrano', 'url': 'https://caminohealthcenter.org'},
    {'name': 'Cares Community Health', 'raw': 'CARES COMMUNITY HEALTH', 'sites': 6, 'counties': ['Sacramento'], 'lookalike': False, 'city': 'Sacramento', 'url': 'https://onecommunityhealth.com'},
    {'name': 'Castle Family Health Centers, Inc.', 'raw': 'CASTLE FAMILY HEALTH CENTERS, INC.', 'sites': 4, 'counties': ['Merced'], 'lookalike': True, 'city': 'Atwater', 'url': None},
    {'name': 'Celebrating Life Community Health Center', 'raw': 'CELEBRATING LIFE COMMUNITY HEALTH CENTER', 'sites': 13, 'counties': ['Orange'], 'lookalike': True, 'city': 'Mission Viejo', 'url': 'https://clchc.org'},
    {'name': 'Center for Family Health & Education Inc.', 'raw': 'CENTER FOR FAMILY HEALTH & EDUCATION INC.', 'sites': 16, 'counties': ['Fresno', 'Los Angeles', 'San Bernardino'], 'lookalike': False, 'city': 'Panorama City', 'url': 'https://cffhae.org'},
    {'name': 'Central City Community Health Center, Inc.', 'raw': 'CENTRAL CITY COMMUNITY HEALTH CENTER, INC', 'sites': 31, 'counties': ['Los Angeles', 'Orange', 'Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'Anaheim', 'url': 'https://centralcityhealth.org'},
    {'name': 'Central Neighborhood Health Foundation', 'raw': 'CENTRAL NEIGHBORHOOD HEALTH FOUNDATION', 'sites': 16, 'counties': ['Los Angeles', 'Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'Los Angeles', 'url': None},
    {'name': 'Centro de Salud de la Comunidad de San Ysidro, Inc.', 'raw': 'CENTRO DE SALUD DE LA COMUNIDAD DE SAN YSIDRO, INC.', 'sites': 50, 'counties': ['San Diego'], 'lookalike': False, 'city': 'Chula Vista', 'url': 'https://syhc.org'},
    {'name': 'Centro Medico Community Clinic, Inc.', 'raw': 'CENTRO MEDICO COMMUNITY CLINIC, INC.', 'sites': 19, 'counties': ['Los Angeles', 'Riverside'], 'lookalike': True, 'city': 'Corona', 'url': 'https://centromedicoclinic.com'},
    {'name': "Children's Hospital & Research Center at Oakland", 'raw': "CHILDREN'S HOSPITAL & RESEARCH CENTER AT OAKLAND", 'sites': 8, 'counties': ['Alameda'], 'lookalike': False, 'city': 'Oakland', 'url': 'https://www.childrenshospitaloakland.org'},
    {'name': 'Chinatown Service Center', 'raw': 'CHINATOWN SERVICE CENTER', 'sites': 17, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://cscla.org'},
    {'name': 'Clinica de Salud del Valle de Salinas', 'raw': 'CLINICA DE SALUD DEL VALLE DE SALINAS', 'sites': 16, 'counties': ['Monterey'], 'lookalike': False, 'city': 'Salinas', 'url': 'https://csvs.org'},
    {'name': 'Clinica MSR. Oscar a Romero', 'raw': 'CLINICA MSR. OSCAR A ROMERO', 'sites': 8, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://clinicaromero.com'},
    {'name': 'Clinica Sierra Vista', 'raw': 'CLINICA SIERRA VISTA', 'sites': 39, 'counties': ['Fresno', 'Kern'], 'lookalike': False, 'city': 'Bakersfield', 'url': 'https://clinicasierravista.org'},
    {'name': 'Clinicas de Salud del Pueblo, Inc.', 'raw': 'CLINICAS DE SALUD DEL PUEBLO, INC', 'sites': 14, 'counties': ['Imperial', 'Riverside'], 'lookalike': False, 'city': 'Brawley', 'url': 'https://innercare.org'},
    {'name': 'Clinicas del Camino Real, Inc.', 'raw': 'CLINICAS DEL CAMINO REAL, INC.', 'sites': 37, 'counties': ['Ventura'], 'lookalike': False, 'city': 'Oxnard', 'url': None},
    {'name': 'Community Health Centers of America', 'raw': 'COMMUNITY HEALTH CENTERS OF AMERICA', 'sites': 16, 'counties': ['Fresno', 'Kern', 'Madera', 'Mariposa', 'Merced', 'Sacramento', 'Stanislaus'], 'lookalike': True, 'city': 'Fresno', 'url': 'https://chcoa.org'},
    {'name': 'Community Health Centers of the Central Coast Inc.', 'raw': 'COMMUNITY HEALTH CENTERS OF THE CENTRAL COAST INC', 'sites': 39, 'counties': ['San Luis Obispo', 'Santa Barbara'], 'lookalike': False, 'city': 'Santa Maria', 'url': 'https://www.chccc.org'},
    {'name': 'Community Health Systems, Inc.', 'raw': 'COMMUNITY HEALTH SYSTEMS, INC.', 'sites': 13, 'counties': ['Riverside', 'San Bernardino', 'San Diego'], 'lookalike': False, 'city': 'Riverside', 'url': 'https://chsica.org'},
    {'name': 'Community Medical Centers, Inc.', 'raw': 'COMMUNITY MEDICAL CENTERS, INC.', 'sites': 40, 'counties': ['San Joaquin', 'Solano'], 'lookalike': False, 'city': 'Stockton', 'url': 'https://www.communitymedicalcenters.org'},
    {'name': 'Community Medical Wellness Centers, USA', 'raw': 'COMMUNITY MEDICAL WELLNESS CENTERS, USA', 'sites': 11, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Long Beach', 'url': 'https://cmwcusa.org'},
    {'name': 'Community Medicine Inc.', 'raw': 'COMMUNITY MEDICINE INC', 'sites': 4, 'counties': ['Los Angeles', 'Orange'], 'lookalike': True, 'city': 'Paramount', 'url': 'https://communitymedicineinc.org'},
    {'name': 'Complete Care Community Health Center, Inc.', 'raw': 'COMPLETE CARE COMMUNITY HEALTH CENTER, INC.', 'sites': 17, 'counties': ['Fresno', 'Los Angeles', 'Orange', 'San Diego', 'Tulare'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://ccchclinic.com'},
    {'name': 'Comprehensive Community Health Centers Inc.', 'raw': 'COMPREHENSIVE COMMUNITY HEALTH CENTERS INC', 'sites': 11, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Glendale', 'url': 'https://cchccenters.org'},
    {'name': 'Coppertower Family Medical Center Inc.', 'raw': 'COPPERTOWER FAMILY MEDICAL CENTER INC', 'sites': 3, 'counties': ['Sonoma'], 'lookalike': False, 'city': 'Cloverdale', 'url': 'https://alexandervalleyhealthcare.org'},
    {'name': 'County of Monterey', 'raw': 'COUNTY OF MONTEREY', 'sites': 14, 'counties': ['Monterey'], 'lookalike': False, 'city': 'Salinas', 'url': None},
    {'name': 'County of Santa Barbara', 'raw': 'COUNTY OF SANTA BARBARA', 'sites': 19, 'counties': ['Santa Barbara'], 'lookalike': False, 'city': 'Santa Barbara', 'url': 'https://sbcphd.org'},
    {'name': 'County of Santa Clara', 'raw': 'COUNTY OF SANTA CLARA', 'sites': 37, 'counties': ['Santa Clara'], 'lookalike': False, 'city': 'San Jose', 'url': None},
    {'name': 'County of Santa Cruz', 'raw': 'COUNTY OF SANTA CRUZ', 'sites': 19, 'counties': ['Santa Cruz'], 'lookalike': False, 'city': 'Santa Cruz', 'url': 'https://santacruzhealth.org'},
    {'name': 'County of Stanislaus', 'raw': 'COUNTY OF STANISLAUS', 'sites': 3, 'counties': ['Stanislaus'], 'lookalike': True, 'city': 'Modesto', 'url': None},
    {'name': 'County of Ventura', 'raw': 'COUNTY OF VENTURA', 'sites': 22, 'counties': ['Ventura'], 'lookalike': False, 'city': 'Oxnard', 'url': None},
    {'name': 'County of Contra Costa', 'raw': 'County of Contra Costa', 'sites': 34, 'counties': ['Contra Costa'], 'lookalike': False, 'city': 'Martinez', 'url': None},
    {'name': 'DAP Health, Inc.', 'raw': 'DAP HEALTH, INC.', 'sites': 30, 'counties': ['Riverside', 'San Diego'], 'lookalike': False, 'city': 'Palm Springs', 'url': None},
    {'name': 'De Novo Health Care, Inc.', 'raw': 'DE NOVO HEALTH CARE, INC', 'sites': 1, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'East Rancho Dominguez', 'url': 'https://denovocare.com'},
    {'name': 'East Valley Community Health Center, Inc.', 'raw': 'EAST VALLEY COMMUNITY HEALTH CENTER, INC', 'sites': 9, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'El Monte', 'url': 'https://evchc.org'},
    {'name': 'El Dorado County Community Health Center', 'raw': 'EL DORADO COUNTY COMMUNITY HEALTH CENTER', 'sites': 7, 'counties': ['El Dorado'], 'lookalike': False, 'city': 'Cameron Park', 'url': 'https://edcchc.org'},
    {'name': 'El Proyecto del Barrio, Inc.', 'raw': 'EL PROYECTO DEL BARRIO, INC.', 'sites': 8, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Winnetka', 'url': None},
    {'name': 'Elica Health CTR', 'raw': 'ELICA HEALTH CTR', 'sites': 16, 'counties': ['Sacramento', 'Yolo'], 'lookalike': False, 'city': 'Sacramento', 'url': 'https://elicahealth.org'},
    {'name': 'Equity Health', 'raw': 'Equity Health', 'sites': 5, 'counties': ['San Francisco'], 'lookalike': False, 'city': 'San Francisco', 'url': 'https://equityhealth.org'},
    {'name': 'Families Together of Orange County', 'raw': 'FAMILIES TOGETHER OF ORANGE COUNTY', 'sites': 12, 'counties': ['Orange'], 'lookalike': True, 'city': 'Tustin', 'url': 'https://familiestogetheroc.org'},
    {'name': 'Family Health Care Centers of Greater Los Angeles Inc.', 'raw': 'FAMILY HEALTH CARE CENTERS OF GREATER LOS ANGELES INC', 'sites': 7, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Bell Gardens', 'url': 'https://fhccgla.com'},
    {'name': 'Family Health Centers of San Diego Inc.', 'raw': 'FAMILY HEALTH CENTERS OF SAN DIEGO INC', 'sites': 75, 'counties': ['San Diego'], 'lookalike': False, 'city': 'San Diego', 'url': 'https://fhcsd.org'},
    {'name': 'Family Healthcare Network', 'raw': 'FAMILY HEALTHCARE NETWORK', 'sites': 50, 'counties': ['Fresno', 'Kern', 'Kings', 'Tulare'], 'lookalike': False, 'city': 'Visalia', 'url': 'https://fhcn.org'},
    {'name': 'Friends of Family Health Center', 'raw': 'FRIENDS OF FAMILY HEALTH CENTER', 'sites': 5, 'counties': ['Los Angeles', 'Orange', 'San Bernardino'], 'lookalike': False, 'city': 'Ontario', 'url': 'https://fofhealthcenter.org'},
    {'name': 'Gardner Family Health Network, Inc.', 'raw': 'GARDNER FAMILY HEALTH NETWORK, INC', 'sites': 16, 'counties': ['San Mateo', 'Santa Clara'], 'lookalike': False, 'city': 'San Jose', 'url': 'https://gardnerhealthservices.org'},
    {'name': 'Garfield Health Center', 'raw': 'GARFIELD HEALTH CENTER', 'sites': 12, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Monterey Park', 'url': None},
    {'name': 'Golden Valley Health Centers', 'raw': 'GOLDEN VALLEY HEALTH CENTERS', 'sites': 54, 'counties': ['Merced', 'San Joaquin', 'Stanislaus'], 'lookalike': False, 'city': 'Modesto', 'url': 'https://www.gvhc.org'},
    {'name': 'Greater Fresno Health Organization, Inc.', 'raw': 'GREATER FRESNO HEALTH ORGANIZATION, INC.', 'sites': 3, 'counties': ['Fresno'], 'lookalike': True, 'city': 'Fresno', 'url': None},
    {'name': 'Greenville Rancheria Tribal Health Program', 'raw': 'GREENVILLE RANCHERIA TRIBAL HEALTH PROGRAM', 'sites': 5, 'counties': ['Shasta', 'Tehama'], 'lookalike': False, 'city': 'Red Bluff', 'url': 'https://greenvillerancheria.com'},
    {'name': 'Gracelight Community Health', 'raw': 'Gracelight Community Health', 'sites': 9, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://gracelight.org'},
    {'name': 'Harbor Community Clinic', 'raw': 'HARBOR COMMUNITY CLINIC', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'San Pedro', 'url': 'https://harborchc.org'},
    {'name': 'Harmony Health Medical Clinic and Family Resource Center', 'raw': 'HARMONY HEALTH MEDICAL CLINIC AND FAMILY RESOURCE CENTER', 'sites': 4, 'counties': ['Sutter', 'Yuba'], 'lookalike': False, 'city': 'Marysville', 'url': 'https://myharmonyhealth.org'},
    {'name': 'Health Access for All Inc.', 'raw': 'HEALTH ACCESS FOR ALL INC.', 'sites': 14, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://angelescommunity.org'},
    {'name': 'Health and Life Organization, Inc. (h.a.l.o)', 'raw': 'HEALTH AND LIFE ORGANIZATION, INC. (H.A.L.O)', 'sites': 10, 'counties': ['Sacramento'], 'lookalike': True, 'city': 'Sacramento', 'url': 'https://halocares.org'},
    {'name': 'Health Service Alliance', 'raw': 'HEALTH SERVICE ALLIANCE', 'sites': 8, 'counties': ['Los Angeles', 'Riverside', 'San Bernardino'], 'lookalike': True, 'city': 'Montclair', 'url': 'https://healthservicealliance.org'},
    {'name': 'Healthright 360', 'raw': 'HEALTHRIGHT 360', 'sites': 2, 'counties': ['San Francisco', 'San Mateo'], 'lookalike': True, 'city': 'San Mateo', 'url': None},
    {'name': 'Herald Christian Health Center', 'raw': 'HERALD CHRISTIAN HEALTH CENTER', 'sites': 8, 'counties': ['Los Angeles', 'San Diego'], 'lookalike': False, 'city': 'El Monte', 'url': 'https://hchcla.org'},
    {'name': 'Hi-desert Memorial Health Care District', 'raw': 'HI-DESERT MEMORIAL HEALTH CARE DISTRICT', 'sites': 10, 'counties': ['San Bernardino'], 'lookalike': False, 'city': 'Yucca Valley', 'url': 'https://mbhdistrict.org'},
    {'name': 'Hill Country Community Clinic', 'raw': 'HILL COUNTRY COMMUNITY CLINIC', 'sites': 8, 'counties': ['Shasta'], 'lookalike': False, 'city': 'Redding', 'url': 'https://hillcountryclinic.org'},
    {'name': 'Hurtt Family Health Clinic, Inc.', 'raw': 'HURTT FAMILY HEALTH CLINIC, INC.', 'sites': 13, 'counties': ['Orange'], 'lookalike': False, 'city': 'Tustin', 'url': 'https://www.hurtclinic.org'},
    {'name': 'Imperial Beach Community Clinic', 'raw': 'IMPERIAL BEACH COMMUNITY CLINIC', 'sites': 4, 'counties': ['San Diego'], 'lookalike': False, 'city': 'San Diego', 'url': 'https://ibclinic.org'},
    {'name': 'Indian Health Center of Santa Clara Valley', 'raw': 'INDIAN HEALTH CENTER OF SANTA CLARA VALLEY', 'sites': 13, 'counties': ['Santa Clara'], 'lookalike': False, 'city': 'San Jose', 'url': 'https://indianhealthcenter.org'},
    {'name': 'Inland Behavioral and Health Services, Inc.', 'raw': 'INLAND BEHAVIORAL AND HEALTH SERVICES, INC.', 'sites': 3, 'counties': ['Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'San Bernardino', 'url': 'https://ibhealth.org'},
    {'name': 'JWCH Institute, Inc.', 'raw': 'JWCH INSTITUTE, INC.', 'sites': 48, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://jwchinstitute.org'},
    {'name': 'Karuk Tribe of California', 'raw': 'KARUK TRIBE OF CALIFORNIA', 'sites': 5, 'counties': ['Humboldt', 'Siskiyou'], 'lookalike': False, 'city': 'Happy Camp', 'url': 'https://karuk.us'},
    {'name': 'KCS, Inc.', 'raw': 'KCS, INC.', 'sites': 8, 'counties': ['Orange'], 'lookalike': False, 'city': 'Buena Park', 'url': 'https://kcsinc.org'},
    {'name': 'Kedren Community Health Center, Inc.', 'raw': 'KEDREN COMMUNITY HEALTH CENTER, INC.', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://kedrenmentalhealth.com'},
    {'name': 'Kern County Hospital Authority', 'raw': 'KERN COUNTY HOSPITAL AUTHORITY', 'sites': 10, 'counties': ['Kern'], 'lookalike': True, 'city': 'Bakersfield', 'url': 'https://kernmedical.com'},
    {'name': 'Korean Health, Education, Information and Research Center', 'raw': 'KOREAN HEALTH, EDUCATION, INFORMATION AND RESEARCH CENTER', 'sites': 7, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://lakheir.org'},
    {'name': 'Kwang He Won Health CTR', 'raw': 'KWANG HE WON HEALTH CTR', 'sites': 5, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://kwanghewon.org'},
    {'name': 'La Clinica de la Raza, Inc.', 'raw': 'LA CLINICA DE LA RAZA, INC.', 'sites': 49, 'counties': ['Alameda', 'Contra Costa', 'Solano'], 'lookalike': False, 'city': 'Oakland', 'url': 'https://laclinica.org'},
    {'name': 'La Maestra Family Clinic, Inc.', 'raw': 'LA MAESTRA FAMILY CLINIC, INC.', 'sites': 31, 'counties': ['San Diego'], 'lookalike': False, 'city': 'San Diego', 'url': 'https://lamaestra.org'},
    {'name': 'Laguna Beach Community Clinic, Inc.', 'raw': 'LAGUNA BEACH COMMUNITY CLINIC, INC', 'sites': 1, 'counties': ['Orange'], 'lookalike': True, 'city': 'Laguna Beach', 'url': 'https://lbclinic.org'},
    {'name': 'Lifelong Medical Care', 'raw': 'LIFELONG MEDICAL CARE', 'sites': 42, 'counties': ['Alameda', 'Contra Costa'], 'lookalike': False, 'city': 'Oakland', 'url': None},
    {'name': 'Livingston Community Health', 'raw': 'LIVINGSTON COMMUNITY HEALTH', 'sites': 11, 'counties': ['Merced', 'Stanislaus'], 'lookalike': False, 'city': 'Waterford', 'url': 'https://lumirahealthcare.com'},
    {'name': 'Long Valley Health Center', 'raw': 'LONG VALLEY HEALTH CENTER', 'sites': 2, 'counties': ['Mendocino'], 'lookalike': False, 'city': 'Laytonville', 'url': 'https://longvalley.org'},
    {'name': 'Los Angeles Christian Health Centers', 'raw': 'LOS ANGELES CHRISTIAN HEALTH CENTERS', 'sites': 10, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://lachc.com'},
    {'name': 'Los Angeles Free Clinic., the', 'raw': 'LOS ANGELES FREE CLINIC., THE', 'sites': 8, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://sabancommunityclinic.org'},
    {'name': 'Los Angeles LGBT Center', 'raw': 'LOS ANGELES LGBT CENTER', 'sites': 8, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://lalgbtcenter.org'},
    {'name': 'Lyon-martin Community Health Services', 'raw': 'LYON-MARTIN COMMUNITY HEALTH SERVICES', 'sites': 1, 'counties': ['San Francisco'], 'lookalike': True, 'city': 'San Francisco', 'url': 'https://lyon-martin.org'},
    {'name': 'Livingstone Community Development Corporation', 'raw': 'Livingstone Community Development Corporation', 'sites': 1, 'counties': ['Orange'], 'lookalike': True, 'city': 'Stanton', 'url': None},
    {'name': 'Marin City Health and Wellness Center', 'raw': 'MARIN CITY HEALTH AND WELLNESS CENTER', 'sites': 7, 'counties': ['Marin', 'San Francisco'], 'lookalike': False, 'city': 'San Rafael', 'url': 'https://marincityclinic.org'},
    {'name': 'Marin Community Clinic', 'raw': 'MARIN COMMUNITY CLINIC', 'sites': 17, 'counties': ['Marin'], 'lookalike': False, 'city': 'San Rafael', 'url': 'https://marinclinic.org'},
    {'name': 'Mccloud Healthcare Clinic, Inc.', 'raw': 'MCCLOUD HEALTHCARE CLINIC, INC', 'sites': 5, 'counties': ['Siskiyou'], 'lookalike': False, 'city': 'Dunsmuir', 'url': 'https://shastacascadehealth.org'},
    {'name': 'Mendocino Coast Clinics Inc.', 'raw': 'MENDOCINO COAST CLINICS INC', 'sites': 7, 'counties': ['Mendocino'], 'lookalike': False, 'city': 'Fort Bragg', 'url': 'https://mendocinocoastclinics.org'},
    {'name': 'Mendocino Community Health Clinic Inc.', 'raw': 'MENDOCINO COMMUNITY HEALTH CLINIC INC', 'sites': 10, 'counties': ['Lake', 'Mendocino'], 'lookalike': False, 'city': 'Ukiah', 'url': 'https://mchcinc.org'},
    {'name': 'Mission Area Health Associates', 'raw': 'MISSION AREA HEALTH ASSOCIATES', 'sites': 4, 'counties': ['San Francisco'], 'lookalike': False, 'city': 'San Francisco', 'url': 'https://mnhc.org'},
    {'name': 'Mission City Community Network, Inc.', 'raw': 'MISSION CITY COMMUNITY NETWORK, INC', 'sites': 19, 'counties': ['Los Angeles', 'Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'North Hills', 'url': 'https://mccn.org'},
    {'name': 'Mountain Valleys Health Centers', 'raw': 'MOUNTAIN VALLEYS HEALTH CENTERS', 'sites': 12, 'counties': ['Lassen', 'Shasta', 'Siskiyou'], 'lookalike': False, 'city': 'Burney', 'url': 'https://mountainvalleys.org'},
    {'name': 'Neighborhood Healthcare', 'raw': 'NEIGHBORHOOD HEALTHCARE', 'sites': 73, 'counties': ['Riverside', 'San Bernardino', 'San Diego'], 'lookalike': False, 'city': 'Escondido', 'url': 'https://nhcare.org'},
    {'name': 'Nhan Hoa Comprehensive Health Care Clinic, Inc.', 'raw': 'NHAN HOA COMPREHENSIVE HEALTH CARE CLINIC, INC.', 'sites': 2, 'counties': ['Orange'], 'lookalike': False, 'city': 'Garden Grove', 'url': 'https://nhanhoa.org'},
    {'name': 'Noalab Clinic Inc.', 'raw': 'NOALAB CLINIC INC', 'sites': 2, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'North Hollywood', 'url': 'https://noalabhealthcare.org'},
    {'name': 'North County Health Project Incorporated', 'raw': 'NORTH COUNTY HEALTH PROJECT INCORPORATED', 'sites': 29, 'counties': ['Riverside', 'San Diego'], 'lookalike': False, 'city': 'Oceanside', 'url': 'https://truecare.org'},
    {'name': 'North East Medical Services', 'raw': 'NORTH EAST MEDICAL SERVICES', 'sites': 37, 'counties': ['San Francisco', 'San Mateo', 'Santa Clara'], 'lookalike': False, 'city': 'San Francisco', 'url': 'https://nems.org'},
    {'name': 'North Orange County Regional Health Foundation', 'raw': 'NORTH ORANGE COUNTY REGIONAL HEALTH FOUNDATION', 'sites': 9, 'counties': ['Orange'], 'lookalike': False, 'city': 'Anaheim', 'url': 'https://fhm-chc.org'},
    {'name': 'Northeast Community Clinic', 'raw': 'NORTHEAST COMMUNITY CLINIC', 'sites': 18, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://necc.net'},
    {'name': 'Northeast Valley Health Corporation', 'raw': 'NORTHEAST VALLEY HEALTH CORPORATION', 'sites': 51, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://nevhc.org'},
    {'name': 'Northeastern Rural Health Clinics', 'raw': 'NORTHEASTERN RURAL HEALTH CLINICS', 'sites': 2, 'counties': ['Lassen'], 'lookalike': False, 'city': 'Susanville', 'url': 'https://northeasternhealth.org'},
    {'name': 'Ole Health', 'raw': 'OLE HEALTH', 'sites': 25, 'counties': ['Napa', 'Solano', 'Yolo'], 'lookalike': False, 'city': 'Woodland', 'url': 'https://clinicole.org'},
    {'name': 'Omni Family Health', 'raw': 'OMNI FAMILY HEALTH', 'sites': 50, 'counties': ['Fresno', 'Kern', 'Kings', 'Tulare'], 'lookalike': False, 'city': 'Bakersfield', 'url': 'https://omnifamilyhealth.org'},
    {'name': 'Open Door Community Health Centers', 'raw': 'OPEN DOOR COMMUNITY HEALTH CENTERS', 'sites': 25, 'counties': ['Del Norte', 'Humboldt'], 'lookalike': False, 'city': 'Eureka', 'url': 'https://opendoorhealth.com'},
    {'name': 'Operation Samahan, Inc.', 'raw': 'OPERATION SAMAHAN, INC.', 'sites': 12, 'counties': ['San Diego'], 'lookalike': False, 'city': 'San Diego', 'url': 'https://opsam.org'},
    {'name': 'Peach Tree Healthcare', 'raw': 'PEACH TREE HEALTHCARE', 'sites': 13, 'counties': ['Butte', 'Sacramento', 'Sutter', 'Yuba'], 'lookalike': False, 'city': 'Marysville', 'url': 'https://pickpeach.org'},
    {'name': 'Pediatric and Family Medical Foundation', 'raw': 'PEDIATRIC AND FAMILY MEDICAL FOUNDATION', 'sites': 22, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://eisnerhealth.org'},
    {'name': 'Peninsula Healthcare Connection, Inc.', 'raw': 'PENINSULA HEALTHCARE CONNECTION, INC.', 'sites': 1, 'counties': ['Santa Clara'], 'lookalike': True, 'city': 'Palo Alto', 'url': 'https://peninsulahcc.org'},
    {'name': 'Petaluma Health Center, Inc.', 'raw': 'PETALUMA HEALTH CENTER, INC.', 'sites': 20, 'counties': ['Marin', 'Sonoma'], 'lookalike': False, 'city': 'Petaluma', 'url': 'https://phealthcenter.org'},
    {'name': 'Pomona Community Health Center', 'raw': 'POMONA COMMUNITY HEALTH CENTER', 'sites': 6, 'counties': ['Los Angeles', 'San Bernardino'], 'lookalike': False, 'city': 'Pomona', 'url': 'https://parktreechc.org'},
    {'name': 'Precision Health Center', 'raw': 'PRECISION HEALTH CENTER', 'sites': 3, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': None},
    {'name': 'Prime Wellness Community Health Center', 'raw': 'PRIME WELLNESS COMMUNITY HEALTH CENTER', 'sites': 1, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://primewellnesschc.org'},
    {'name': 'Redwood Coast Medical Services, Inc.', 'raw': 'REDWOOD COAST MEDICAL SERVICES, INC.', 'sites': 5, 'counties': ['Mendocino'], 'lookalike': False, 'city': 'Gualala', 'url': 'https://www.rcms-healthcare.org'},
    {'name': 'Redwoods Rural Health Center, Incorporated', 'raw': 'REDWOODS RURAL HEALTH CENTER, INCORPORATED', 'sites': 10, 'counties': ['Humboldt'], 'lookalike': False, 'city': 'Redway', 'url': 'https://rrhc.org'},
    {'name': 'Ritter Center', 'raw': 'RITTER CENTER', 'sites': 4, 'counties': ['Marin'], 'lookalike': False, 'city': 'San Rafael', 'url': 'https://rittercenter.org'},
    {'name': 'County of Riverside', 'raw': 'RIVERSIDE, COUNTY OF', 'sites': 18, 'counties': ['Riverside'], 'lookalike': False, 'city': 'Moreno Valley', 'url': 'https://ruhealth.org'},
    {'name': 'SAC Health System', 'raw': 'SAC HEALTH SYSTEM', 'sites': 26, 'counties': ['Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'San Bernardino', 'url': None},
    {'name': 'Sacramento County Primary', 'raw': 'SACRAMENTO COUNTY PRIMARY', 'sites': 35, 'counties': ['Sacramento'], 'lookalike': False, 'city': 'Sacramento', 'url': 'https://fcusd.org'},
    {'name': 'Saint Youstina', 'raw': 'SAINT YOUSTINA', 'sites': 3, 'counties': ['Orange'], 'lookalike': True, 'city': 'Santa Ana', 'url': 'https://styoustina.org'},
    {'name': 'Salud Para la Gente', 'raw': 'SALUD PARA LA GENTE', 'sites': 15, 'counties': ['Monterey', 'Santa Cruz'], 'lookalike': False, 'city': 'Watsonville', 'url': 'https://splg.org'},
    {'name': 'Samuel Dixon Family Health Center, Inc.', 'raw': 'SAMUEL DIXON FAMILY HEALTH CENTER, INC.', 'sites': 6, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Valencia', 'url': 'https://sdfhc.org'},
    {'name': 'San Benito Health Foundation', 'raw': 'SAN BENITO HEALTH FOUNDATION', 'sites': 2, 'counties': ['San Benito'], 'lookalike': False, 'city': 'Hollister', 'url': None},
    {'name': 'San Bernardino Public Health', 'raw': 'SAN BERNARDINO PUBLIC HEALTH', 'sites': 7, 'counties': ['San Bernardino'], 'lookalike': False, 'city': 'Ontario', 'url': 'https://sbcounty.gov'},
    {'name': 'San Diego American Indian Health Center', 'raw': 'SAN DIEGO AMERICAN INDIAN HEALTH CENTER', 'sites': 5, 'counties': ['San Diego'], 'lookalike': False, 'city': 'San Diego', 'url': 'https://sdaihc.org'},
    {'name': 'San Diego Family Care', 'raw': 'SAN DIEGO FAMILY CARE', 'sites': 8, 'counties': ['San Diego'], 'lookalike': False, 'city': 'San Diego', 'url': 'https://sdfamilycare.org'},
    {'name': 'San Fernando Community Hospital', 'raw': 'SAN FERNANDO COMMUNITY HOSPITAL', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'San Fernando', 'url': 'https://sfchealthcenter.org'},
    {'name': 'San Francisco Community Clinic Consortium', 'raw': 'SAN FRANCISCO COMMUNITY CLINIC CONSORTIUM', 'sites': 43, 'counties': ['San Francisco'], 'lookalike': False, 'city': 'San Francisco', 'url': 'https://mnhc.org'},
    {'name': 'San Joaquin County Health Services Employees Guild', 'raw': 'SAN JOAQUIN COUNTY HEALTH SERVICES EMPLOYEES GUILD', 'sites': 9, 'counties': ['San Joaquin'], 'lookalike': True, 'city': 'French Camp', 'url': 'https://sjhealth.org'},
    {'name': 'San Judas Community Health Center Inc.', 'raw': 'SAN JUDAS COMMUNITY HEALTH CENTER INC', 'sites': 2, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://sanjudaschc.org'},
    {'name': 'Santa Barbara Neighborhood Clinics', 'raw': 'SANTA BARBARA NEIGHBORHOOD CLINICS', 'sites': 11, 'counties': ['Santa Barbara'], 'lookalike': False, 'city': 'Santa Barbara', 'url': 'https://sbclinics.org'},
    {'name': 'Santa Cruz Community Health Centers', 'raw': 'SANTA CRUZ COMMUNITY HEALTH CENTERS', 'sites': 9, 'counties': ['Santa Cruz'], 'lookalike': False, 'city': 'Santa Cruz', 'url': 'https://lo.losd.ca'},
    {'name': 'Santa Rosa Community Health Centers', 'raw': 'SANTA ROSA COMMUNITY HEALTH CENTERS', 'sites': 15, 'counties': ['Sonoma'], 'lookalike': False, 'city': 'Santa Rosa', 'url': 'https://srhealth.org'},
    {'name': 'Santo Nino Health Center', 'raw': 'SANTO NINO HEALTH CENTER', 'sites': 5, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Panorama City', 'url': 'https://santoninohc.org'},
    {'name': 'School Health Clinics of Santa Clara County', 'raw': 'SCHOOL HEALTH CLINICS OF SANTA CLARA COUNTY', 'sites': 6, 'counties': ['Santa Clara'], 'lookalike': False, 'city': 'San Jose', 'url': None},
    {'name': 'Serenity Care Health Group', 'raw': 'SERENITY CARE HEALTH GROUP', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Long Beach', 'url': 'https://serenitycarehealthgroup.org'},
    {'name': 'Serve the People, Inc.', 'raw': 'SERVE THE PEOPLE, INC', 'sites': 12, 'counties': ['Orange'], 'lookalike': False, 'city': 'Santa Ana', 'url': 'https://serve-the-people.com'},
    {'name': 'SFV Health Center, Inc.', 'raw': 'SFV HEALTH CENTER, INC', 'sites': 5, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Sun Valley', 'url': 'https://elevatehealthcenter.org'},
    {'name': 'Share Our Selves Corporation', 'raw': 'SHARE OUR SELVES CORPORATION', 'sites': 10, 'counties': ['Orange'], 'lookalike': False, 'city': 'Newport Beach', 'url': 'https://shareourselves.org'},
    {'name': 'Shasta Community Health Center', 'raw': 'SHASTA COMMUNITY HEALTH CENTER', 'sites': 14, 'counties': ['Shasta'], 'lookalike': False, 'city': 'Redding', 'url': 'https://shastahealth.org'},
    {'name': 'Shingletown Medical Center', 'raw': 'SHINGLETOWN MEDICAL CENTER', 'sites': 1, 'counties': ['Shasta'], 'lookalike': False, 'city': 'Shingletown', 'url': 'https://shingletownmedcenter.org'},
    {'name': 'So-cal Community Health Center', 'raw': 'SO-CAL COMMUNITY HEALTH CENTER', 'sites': 2, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'North Hills', 'url': 'https://socalchc.org'},
    {'name': 'Solano County Health & Social Services Department', 'raw': 'SOLANO COUNTY HEALTH & SOCIAL SERVICES DEPARTMENT', 'sites': 8, 'counties': ['Solano'], 'lookalike': False, 'city': 'Fairfield', 'url': 'https://solanocounty.com'},
    {'name': 'Sonoma Valley Community Health Center', 'raw': 'SONOMA VALLEY COMMUNITY HEALTH CENTER', 'sites': 2, 'counties': ['Sonoma'], 'lookalike': False, 'city': 'Sonoma', 'url': None},
    {'name': 'South Central Family Health Center', 'raw': 'SOUTH CENTRAL FAMILY HEALTH CENTER', 'sites': 15, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://scfhc.org'},
    {'name': 'South County Community Health Center, Inc.', 'raw': 'SOUTH COUNTY COMMUNITY HEALTH CENTER, INC.', 'sites': 17, 'counties': ['San Mateo', 'Santa Clara'], 'lookalike': False, 'city': 'East Palo Alto', 'url': 'https://ravenswoodfhc.org'},
    {'name': 'Southern California Medical Center, Inc.', 'raw': 'SOUTHERN CALIFORNIA MEDICAL CENTER, INC.', 'sites': 9, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'San Dimas', 'url': 'https://scmedcenter.org'},
    {'name': 'Southland Integrated Services Inc.', 'raw': 'SOUTHLAND INTEGRATED SERVICES INC', 'sites': 2, 'counties': ['Orange'], 'lookalike': False, 'city': 'Garden Grove', 'url': 'https://southlandintegrated.org'},
    {'name': 'ST. Anthony Medical Centers, a Nonprofit Corporation', 'raw': 'ST. ANTHONY MEDICAL CENTERS, A NONPROFIT CORPORATION', 'sites': 5, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': None},
    {'name': "ST. John's Community Health", 'raw': "ST. JOHN'S COMMUNITY HEALTH", 'sites': 29, 'counties': ['Los Angeles', 'Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://wellchild.org'},
    {'name': 'ST. Jude Neighborhood Health Centers', 'raw': 'ST. JUDE NEIGHBORHOOD HEALTH CENTERS', 'sites': 14, 'counties': ['Orange', 'San Bernardino'], 'lookalike': False, 'city': 'Orange', 'url': 'https://stjudenhc.org'},
    {'name': 'ST. Vincent de Paul Village, Inc.', 'raw': 'ST. VINCENT DE PAUL VILLAGE, INC.', 'sites': 1, 'counties': ['San Diego'], 'lookalike': False, 'city': 'San Diego', 'url': 'https://my.neighbor.org'},
    {'name': 'San Mateo County Health', 'raw': 'San Mateo County Health', 'sites': 20, 'counties': ['San Mateo'], 'lookalike': False, 'city': 'San Mateo', 'url': 'https://www.co.sanmateo.ca.us'},
    {'name': 'Tarzana Treatment Centers, Inc.', 'raw': 'TARZANA TREATMENT CENTERS, INC.', 'sites': 11, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Tarzana', 'url': None},
    {'name': 'Tender Care Community Clinic Inc.', 'raw': 'TENDER CARE COMMUNITY CLINIC INC', 'sites': 1, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Downey', 'url': None},
    {'name': 'The Achievable Foundation', 'raw': 'THE ACHIEVABLE FOUNDATION', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Culver City', 'url': 'https://achievable.org'},
    {'name': 'The Asian Americans for Community Involvement of Santa Clara County, Inc.', 'raw': 'THE ASIAN AMERICANS FOR COMMUNITY INVOLVEMENT OF SANTA CLARA COUNTY, INC.', 'sites': 5, 'counties': ['Santa Clara'], 'lookalike': False, 'city': 'San Jose', 'url': 'https://aaci.org'},
    {'name': 'The Clinic, Inc.', 'raw': 'THE CLINIC, INC.', 'sites': 7, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://tohelpeveryone.org'},
    {'name': 'The Davis Street Community Center Incorporated', 'raw': 'THE DAVIS STREET COMMUNITY CENTER INCORPORATED', 'sites': 1, 'counties': ['Alameda'], 'lookalike': False, 'city': 'San Leandro', 'url': 'https://davisstreet.org'},
    {'name': 'The R.O.A.D.S. Foundation, Inc.', 'raw': 'THE R.O.A.D.S. FOUNDATION, INC.', 'sites': 9, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Long Beach', 'url': 'https://roadsfoundation.org'},
    {'name': 'The West Oakland Health Council', 'raw': 'THE WEST OAKLAND HEALTH COUNCIL', 'sites': 6, 'counties': ['Alameda'], 'lookalike': False, 'city': 'Oakland', 'url': None},
    {'name': 'Tiburcio Vasquez Health Center, Incorporated', 'raw': 'TIBURCIO VASQUEZ HEALTH CENTER, INCORPORATED', 'sites': 20, 'counties': ['Alameda'], 'lookalike': False, 'city': 'Hayward', 'url': 'https://tvhc.org'},
    {'name': 'TL Health Care Foundation', 'raw': 'TL HEALTH CARE FOUNDATION', 'sites': 1, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'San Gabriel', 'url': 'https://tlhcare.org'},
    {'name': 'Todos Para la Salud', 'raw': 'TODOS PARA LA SALUD', 'sites': 4, 'counties': ['Fresno', 'Los Angeles'], 'lookalike': True, 'city': 'Fresno', 'url': 'https://todosclinic.com'},
    {'name': 'Tri-state Community Healthcare Center', 'raw': 'TRI-STATE COMMUNITY HEALTHCARE CENTER', 'sites': 23, 'counties': ['Los Angeles', 'Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://tristateclinics.org'},
    {'name': 'County of Tulare', 'raw': 'TULARE, COUNTY OF', 'sites': 2, 'counties': ['Tulare'], 'lookalike': True, 'city': 'Visalia', 'url': None},
    {'name': "The Children's Clinic, Serving Children and Their Families", 'raw': "The Children's Clinic, Serving Children And Their Families", 'sites': 14, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Long Beach', 'url': 'https://thechildrensclinic.org'},
    {'name': 'The Wecare Group', 'raw': 'The WeCare Group', 'sites': 3, 'counties': ['Humboldt', 'Trinity'], 'lookalike': False, 'city': 'Scotia', 'url': 'https://sthsclinic.org'},
    {'name': 'Unicare Community Health Center, Inc.', 'raw': 'UNICARE COMMUNITY HEALTH CENTER, INC', 'sites': 23, 'counties': ['Los Angeles', 'Riverside', 'San Bernardino'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://unicarechc.org'},
    {'name': 'United Health Centers of the San Joaquin Valley', 'raw': 'UNITED HEALTH CENTERS OF THE SAN JOAQUIN VALLEY', 'sites': 55, 'counties': ['Fresno', 'Kern', 'Kings', 'Tulare'], 'lookalike': False, 'city': 'Fresno', 'url': 'https://unitedhealthcenters.org'},
    {'name': 'Universal Community Health Center', 'raw': 'UNIVERSAL COMMUNITY HEALTH CENTER', 'sites': 11, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://uchcla.org'},
    {'name': 'University Muslim Medical Association, Inc.', 'raw': 'UNIVERSITY MUSLIM MEDICAL ASSOCIATION, INC', 'sites': 11, 'counties': ['Los Angeles', 'San Bernardino'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://ummaclinic.org'},
    {'name': 'University of California Irvine', 'raw': 'UNIVERSITY OF CALIFORNIA IRVINE', 'sites': 3, 'counties': ['Orange'], 'lookalike': False, 'city': 'Santa Ana', 'url': 'https://ucirvinehealth.org'},
    {'name': 'Valley Community Healthcare', 'raw': 'VALLEY COMMUNITY HEALTHCARE', 'sites': 3, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'North Hollywood', 'url': 'https://valleycommunityhealthcare.org'},
    {'name': 'Valley Health Team, Inc.', 'raw': 'VALLEY HEALTH TEAM, INC.', 'sites': 19, 'counties': ['Fresno', 'Inyo', 'Tulare'], 'lookalike': False, 'city': 'Kerman', 'url': 'https://vht.org'},
    {'name': 'Venice Family Clinic', 'raw': 'VENICE FAMILY CLINIC', 'sites': 25, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Venice', 'url': 'https://venicefamilyclinic.org'},
    {'name': 'Via Care Community Health Center', 'raw': 'VIA CARE COMMUNITY HEALTH CENTER', 'sites': 26, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://viacarela.org'},
    {'name': 'Vista Community Clinic', 'raw': 'VISTA COMMUNITY CLINIC', 'sites': 23, 'counties': ['Los Angeles', 'Orange', 'Riverside', 'San Diego'], 'lookalike': False, 'city': 'Vista', 'url': 'https://vcc.org'},
    {'name': 'Watts Healthcare Corp.', 'raw': 'WATTS HEALTHCARE CORP', 'sites': 8, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Los Angeles', 'url': 'https://wattshealth.org'},
    {'name': 'Wellspace Health', 'raw': 'WELLSPACE HEALTH', 'sites': 33, 'counties': ['Amador', 'Placer', 'Sacramento'], 'lookalike': False, 'city': 'Sacramento', 'url': 'https://wellspacehealth.org'},
    {'name': 'West County Health Centers, Inc.', 'raw': 'WEST COUNTY HEALTH CENTERS, INC', 'sites': 13, 'counties': ['Sonoma'], 'lookalike': False, 'city': 'Sebastopol', 'url': 'https://www.wchealth.org'},
    {'name': 'Western Sierra Medical Clinic, Inc.', 'raw': 'WESTERN SIERRA MEDICAL CLINIC, INC.', 'sites': 14, 'counties': ['Nevada', 'Placer', 'Sierra', 'Yuba'], 'lookalike': False, 'city': 'Grass Valley', 'url': 'https://wsmcmed.org'},
    {'name': 'Westside Family Health Center', 'raw': 'WESTSIDE FAMILY HEALTH CENTER', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Culver City', 'url': 'https://wfhcenter.org'},
    {'name': 'White Memorial Community Health Center, a California Nonprofit Public Benefit Corporation', 'raw': 'WHITE MEMORIAL COMMUNITY HEALTH CENTER, A CALIFORNIA NONPROFIT PUBLIC BENEFIT CORPORATION', 'sites': 6, 'counties': ['Los Angeles'], 'lookalike': True, 'city': 'Los Angeles', 'url': 'https://wmchealthcenter.org'},
    {'name': 'Wilmington Community Clinic', 'raw': 'WILMINGTON COMMUNITY CLINIC', 'sites': 4, 'counties': ['Los Angeles'], 'lookalike': False, 'city': 'Wilmington', 'url': 'https://wilmingtoncc.org'},
    {'name': 'Winters Healthcare Foundation Inc.', 'raw': 'WINTERS HEALTHCARE FOUNDATION INC', 'sites': 1, 'counties': ['Yolo'], 'lookalike': False, 'city': 'Winters', 'url': 'https://wintershealth.org'},
    {'name': 'Yehowa Medical Services', 'raw': 'YEHOWA MEDICAL SERVICES', 'sites': 10, 'counties': ['Los Angeles', 'Orange'], 'lookalike': False, 'city': 'South Gate', 'url': 'https://ymedical.org'},
]

LINKED = 189
UNLINKED = 29
TOTAL_SITES = 3038
COUNTIES = 52
