# -*- coding: utf-8 -*-
"""The California PsyD data, as researched from primary sources only.

EVERY FIGURE HERE CAME FROM THE INSTITUTION'S OWN PAGE OR FROM APA'S OWN
NOTICE OF ACTIONS. No aggregator was used, and where a school publishes
nothing the value is None and the page says "not published" rather than
carrying an estimate.

apa: one of
  "full"        Accredited, no qualifier
  "contingency" Accredited, on contingency - real accreditation, granted to a
                program too new to have outcome data yet
  "inactive"    Accredited, Inactive - a teach-out; not open to applicants
  "none"        Not APA-accredited
  "closed"      the program no longer exists
"""

PROGRAMS = [
    # ---------------------------------------------------------------- full
    dict(inst="Alliant International University (CSPP), Los Angeles",
         city="Alhambra", apa="full", apa_since="1991", apa_next="2033",
         degree="PsyD in Clinical Psychology",
         units="120 semester units, including 30 internship units",
         length="4 years including a one-year internship; a 5-year plan is offered",
         fmt="On-campus. APA's distance-education list includes all five CSPP PsyD programs as offering at least one course by distance.",
         per_unit=1505, total=None, tyear="2026-27",
         turl="https://www.alliant.edu/admissions/tuition-and-fees",
         url="https://www.alliant.edu/clinical-psychology/psyd-los-angeles",
         note="Alliant tells applicants that “completion of an APA-accredited internship is not required to complete the program.” That is worth reading twice: the VA and many postdocs require one."),
    dict(inst="Alliant International University (CSPP), San Diego",
         city="San Diego", apa="full", apa_since="1994", apa_next="2035",
         degree="PsyD in Clinical Psychology",
         units="120 semester units, including 30 internship units",
         length="4 years including a one-year internship; a 5-year plan is offered",
         fmt="On-campus", per_unit=1505, total=None, tyear="2026-27",
         turl="https://www.alliant.edu/admissions/tuition-and-fees",
         url="https://www.alliant.edu/clinical-psychology/psyd",
         note=None),
    dict(inst="Alliant International University (CSPP), San Francisco Bay",
         city="Emeryville", apa="full", apa_since="1995", apa_next="2033",
         degree="PsyD in Clinical Psychology",
         units="120 semester units, including 30 internship units",
         length="4 years including a one-year internship; a 5-year plan is offered",
         fmt="On-campus", per_unit=1505, total=None, tyear="2026-27",
         turl="https://www.alliant.edu/admissions/tuition-and-fees",
         url="https://www.alliant.edu/clinical-psychology/psyd-san-francisco",
         note=None),
    dict(inst="Alliant International University (CSPP), Sacramento",
         city="Sacramento", apa="full", apa_since="1994", apa_next="2028",
         degree="PsyD in Clinical Psychology",
         units="120 semester units, including 30 internship units",
         length="4 years including a one-year internship; a 5-year plan is offered",
         fmt="On-campus", per_unit=1505, total=None, tyear="2026-27",
         turl="https://www.alliant.edu/admissions/tuition-and-fees",
         url="https://www.alliant.edu/clinical-psychology/psyd", note=None),
    dict(inst="Alliant International University (CSPP), Fresno",
         city="Fresno", apa="full", apa_since="1994", apa_next=None,
         degree="PsyD in Clinical Psychology",
         units="120 semester units, including 30 internship units",
         length="4 years including a one-year internship; a 5-year plan is offered",
         fmt="On-campus", per_unit=1505, total=None, tyear="2026-27",
         turl="https://www.alliant.edu/admissions/tuition-and-fees",
         url="https://www.alliant.edu/clinical-psychology/psyd", note=None),

    dict(inst="Azusa Pacific University", city="Azusa",
         apa="full", apa_since="2000", apa_next=None,
         degree="Doctor of Psychology (PsyD) in Clinical Psychology",
         units="133 semester units (125 required, 8 elective)",
         length="5–6 years", fmt="On-campus, one cohort admitted each fall",
         per_unit=1165, total=154945, tyear="2026-27",
         turl="https://www.apu.edu/graduateprofessional/sfs/costs/",
         url="https://www.apu.edu/programs/psyd/",
         note="Christian, practitioner-scholar, with declared emphases in systems/family psychology, diversity, and integration of faith with practice. An MA in Clinical Psychology is awarded en route after 57 units."),
    dict(inst="Biola University (Rosemead School of Psychology)", city="La Mirada",
         apa="full", apa_since="1980", apa_next="2029",
         degree="Psy.D. in Clinical Psychology", units="123 semester credits",
         length="5–6 years", fmt="On-campus",
         per_unit=None, total=158698, tyear="2026-27",
         turl="https://www.biola.edu/financial-aid/tuition-costs/grad",
         url="https://www.biola.edu/degrees/g/clinical-psychology-psyd",
         note="15 credits of theology and 9 of psychology-theology integration are inside the degree and inside the comprehensive exams. Rosemead runs a separately APA-accredited Clinical PhD as the research track; the PsyD is the practitioner one."),
    dict(inst="California Baptist University", city="Riverside",
         apa="full", apa_since="2021", apa_next="2035",
         degree="Doctor of Psychology (PsyD) in Clinical Psychology",
         units="128 units", length="5 years",
         fmt="On-campus, full-time cohort, fall start only",
         per_unit=1111, total=None, tyear="2025-26",
         turl="https://calbaptist.edu/academics/programs/doctor-of-psychology-clinical-psychology/",
         url="https://calbaptist.edu/academics/programs/doctor-of-psychology-clinical-psychology/",
         note="APA moved this program from contingency to full accreditation at its April 2026 meeting, with the maximum ten-year horizon. CBU's own site had not caught up at the time of checking and still described it as on contingency."),
    dict(inst="California Lutheran University", city="Thousand Oaks / Oxnard",
         apa="full", apa_since="2015", apa_next="2034",
         degree="PsyD in Clinical Psychology", units="114 semester credits",
         length="5 years", fmt="On-campus, fall start",
         per_unit=1190, total=None, tyear="2026-27",
         turl="https://www.callutheran.edu/academics/graduate/psyd-clinical-psychology/tuition-fees.html",
         url="https://www.callutheran.edu/academics/graduate/psyd-clinical-psychology/",
         note="Two of its own full-time training clinics, so early clinical hours are in-house rather than dependent on external placements. Cal Lutheran's page says Thousand Oaks; APA's record says Oxnard — worth asking which campus classes actually meet on."),
    dict(inst="California Northstate University", city="Rancho Cordova",
         apa="full", apa_since="2021", apa_next="2034",
         degree="Doctor of Psychology (PsyD), Clinical Psychology",
         units="148 credit hours", length="5 years, and no student may finish in under four",
         fmt="On-campus, full-time cohort",
         per_unit=None, total=172148, tyear="2025-26",
         turl="https://www.cnsu.edu/financial-aid/PDFs/PSY/PSY_25_26_Tuition_Fees.pdf",
         url="https://www.psychology.cnsu.edu/",
         note="Inside a health-sciences university alongside MD, PharmD and DMD programs. One of the very few that publishes a full five-year total cost, itemised year by year."),
    dict(inst="Fuller Theological Seminary", city="Pasadena",
         apa="full", apa_since="1972", apa_next=None,
         degree="Doctor of Psychology in Clinical Psychology (PsyD)",
         units="242 quarter units", length="5 years",
         fmt="On-campus", per_unit=740, total=145860, tyear="2026-27",
         turl="https://fuller.edu/paying-for-grad-school/",
         url="https://fuller.edu/psyd-clinical-psychology/",
         note="The oldest APA-accredited PsyD in the state. 28 units of theology and 20 of psychology-theology integration are built into the degree, which is why the unit count is roughly double a semester-unit program's. Tracks in Neuropsychology or Culture and Community."),
    dict(inst="Loma Linda University", city="Loma Linda",
         apa="full", apa_since="1998", apa_next=None,
         degree="Doctor of Psychology (PsyD) in Clinical Psychology",
         units="122 quarter units of coursework plus 80 of clinical practice",
         length="5 years including internship", fmt="On-campus, full-time required",
         per_unit=None, total=None, tyear="2026-27",
         turl="https://llu.edu/academics/programs/school-behavioral-health/psychology-psyd-clinical",
         url="https://behavioralhealth.llu.edu/academics/psychology/clinical-psychology-psyd",
         note="Publishes a year-by-year cost of attendance rather than a program total: $38,031 for year one, then $46,158 for years two to four. Inside a Seventh-day Adventist academic health system, so placements skew medical. Optional specialisations in health psychology, neuropsychology and clinical child."),
    dict(inst="Mount Saint Mary's University", city="Los Angeles",
         apa="contingency", apa_since="2024", apa_next="2029",
         degree="PsyD in Clinical Psychology, with a Latinx Mental Health or Diverse Populations emphasis",
         units="120 instructional units plus 9 internship units",
         length="5 years", fmt="In person; classes Tuesdays and Thursdays, first-years also on Fridays",
         per_unit=1247, total=None, tyear="2026-27",
         turl="https://www.msmu.edu/departments/psychology/graduate-programs/clinical-psychology-psyd/tuition-financial-aid/",
         url="https://www.msmu.edu/graduate-programs/clinical-psychology-psyd/",
         note="The only California PsyD with a Latinx Mental Health emphasis, and it funds students through paid teaching and research assistantships — uncommon at a practitioner-model PsyD. Its APA response is due 1 May 2027."),
    dict(inst="National University (JFK School of Psychology)", city="Pleasant Hill",
         apa="full", apa_since="2024", apa_next="2034",
         degree="Doctor of Psychology (PsyD) in Clinical Psychology",
         units="120 semester credit hours", length="5 to 7 years",
         fmt="In person, on the Pleasant Hill campus",
         per_unit=886, total=None, tyear="2024-25",
         turl="https://www.nu.edu/wp-content/uploads/2023/10/Student-Admissions-Outcomes-and-Other-Data.pdf",
         url="https://www.nu.edu/degrees/jfk-psychology/programs/doctor-of-clinical-psychology/",
         note="The successor to John F. Kennedy University's PsyD, on the same campus, with a fresh ten-year accreditation of its own granted in March 2024. At about $40,756 a year it is materially cheaper than the other private PsyDs — though the only published figures are in its APA disclosure, not on its tuition page. Do not confuse it with National's online PhD in Psychology, which is not APA-accredited and is not a licensure path."),
    dict(inst="Palo Alto University (PAU–Stanford PsyD Consortium)", city="Palo Alto",
         apa="full", apa_since="2006", apa_next="2029",
         degree="Doctor of Psychology in Clinical Psychology",
         units="172 quarter units, including at least 32 dissertation units",
         length="4 academic years in residence plus a 2,000-hour APA-accredited internship",
         fmt="On-campus, full-time",
         per_unit=None, total=None, tyear="2026-27",
         turl="https://paloaltou.edu/hubfs/2026-27%20Tuition%20and%20Fees%20Schedule%20for%20NEW%20Students.pdf",
         url="https://paloaltou.edu/academic-programs/pau-stanford-psyd-consortium",
         note="A real two-institution consortium: faculty from PAU and Stanford's Department of Psychiatry, the program describes itself as 50% Stanford-affiliated, and the diploma is signed by both. Flat quarterly tuition of $21,048 for years one to three, so transferring units in does not reduce what you pay. Roughly 30 places from 650–750 applications."),
    dict(inst="Pepperdine University (GSEP)", city="Los Angeles",
         apa="full", apa_since="1990", apa_next="2027",
         degree="PsyD in Clinical Psychology", units="82 units",
         length="4 years by design; the recent median has been 5",
         fmt="In person, daytime; two days a week in years one and two, one day in year three",
         per_unit=2085, total=None, tyear="2026-27",
         turl="https://gsep.pepperdine.edu/admission/tuition/",
         url="https://gsep.pepperdine.edu/doctorate-clinical-psychology/",
         note="The shortest unit count of any California PsyD, which reflects a genuinely four-year design. First-year practicum runs inside Pepperdine's own four community clinics. Its program page and its tuition page disagree on the per-unit rate; the figure here is from the official tuition table."),
    dict(inst="The Chicago School, Los Angeles", city="Los Angeles",
         apa="full", apa_since="2018", apa_next="2028",
         degree="Psy.D. Clinical Psychology", units="106 credit hours",
         length="5 years full time, 7 maximum", fmt="Campus-based",
         per_unit=1879, total=192390, tyear="2026-27",
         turl="https://www.thechicagoschool.edu/admissions/financing-your-education/tuition-fees/psyd-clinical-psychology-los-angeles/",
         url="https://www.thechicagoschool.edu/programs/psychology/clinical-psychology/psyd-los-angeles/",
         note="Do not confuse this with the school's online PsyD in Applied Clinical Psychology, which is a different, non-licensure-track degree and is not APA-accredited."),
    dict(inst="The Chicago School, Anaheim", city="Anaheim",
         apa="full", apa_since="2021", apa_next="2030",
         degree="PsyD in Clinical Psychology", units="98 credit hours",
         length="5 years full time, 7 maximum", fmt="Campus-based",
         per_unit=1879, total=177871, tyear="2026-27",
         turl="https://www.thechicagoschool.edu/admissions/financing-your-education/tuition-fees/psyd-clinical-psychology-anaheim/",
         url="https://www.thechicagoschool.edu/programs/psychology/clinical-psychology/psyd-anaheim/",
         note="This is the former Irvine program. It was created at Irvine in 2019 to let students from the collapsed Argosy University finish their degrees, and moved to Anaheim in 2021. There is no Chicago School PsyD in Irvine or San Diego."),
    dict(inst="The Wright Institute", city="Berkeley",
         apa="full", apa_since="1998", apa_next="2027",
         degree="Doctor of Psychology (Psy.D.) in Clinical Psychology",
         units="Not published — deliberately. “The curriculum is requirement based not unit based.”",
         length="5 years: three in residence, then dissertation and internship",
         fmt="On-campus, Berkeley, trimester calendar",
         per_unit=None, total=None, tyear="2026-27",
         turl="https://www.wi.edu/psyd-tuition",
         url="https://www.wi.edu/psyd-program",
         note="A freestanding professional school — the PsyD and one MA are the whole institution. Flat rate of $45,600 a year for years one to three, then $19,500 on reduced-tuition status and $5,950 during internship, so the total depends on how long the dissertation takes. Theoretically pluralistic rather than one orientation, with both a psychodynamic and a CBT clinic in-house."),
    dict(inst="University of La Verne", city="La Verne",
         apa="full", apa_since="2003", apa_next="2028",
         degree="Doctor of Clinical Psychology (PsyD)",
         units="120 semester hours", length="5 years, full time",
         fmt="On-campus, full-time cohort of 12–14",
         per_unit=1350, total=None, tyear="2026-27",
         turl="https://www.laverne.edu/tuition/2026-2027-graduate-programs-tuition-and-fees/",
         url="https://health.laverne.edu/psyd/",
         note="A 12–14 student cohort with graduate assistantships offered to every first-year, and an explicit requirement of at least 20 hours of personal psychotherapy during training."),

    # ------------------------------------------------------------- inactive
    dict(inst="University of San Francisco", city="San Francisco",
         apa="inactive", apa_since="2018", apa_next="2033",
         degree="Clinical Psychology, PsyD", units="Not published",
         length="4 years plus a fifth-year internship of 1,500–2,000 hours",
         fmt="In person — teach-out only", per_unit=None, total=None,
         tyear=None, turl=None,
         url="https://www.usfca.edu/nursing/programs/graduate/clinical-psychology/program-overview",
         note="Closed to applicants. USF: “Starting in the Fall of 2025, the program is phasing out our existing program and is no longer admitting students.” Accreditation is held open so enrolled students still graduate from an accredited program. Several legacy pages on USF's own site still advertise application deadlines — they are stale."),

    # ----------------------------------------------------------------- none
    dict(inst="California Institute of Integral Studies", city="San Francisco",
         apa="none", apa_since=None, apa_next=None,
         degree="Doctor of Clinical Psychology (PsyD)",
         units="99.1–110.4 semester units", length="5 years minimum",
         fmt="On-campus", per_unit=1587, total=None, tyear="2025-26",
         turl="https://www.ciis.edu/admissions-and-financial-aid/costs-and-aid/tuition-and-fees",
         url="https://www.ciis.edu/academics/graduate-programs/clinical-psychology/about-the-psyd",
         note="CIIS held APA accreditation once and gave it up, and says so: “As a non-APA accredited program, we are not limited by the American Psychological Association’s narrow view of the field.” That is a real philosophical position and it has real consequences — see what accreditation actually decides, above."),
    dict(inst="Meridian University", city="Santa Monica, Petaluma, and online",
         apa="none", apa_since=None, apa_next=None,
         degree="PsyD in Clinical Psychology",
         units="108 credits plus 25 of fieldwork from a bachelor’s; 92 plus 25 with Advanced Standing",
         length="33–48 months, eight-year maximum",
         fmt="Hybrid and online, low-residency",
         per_unit=676, total=None, tyear="2026-27",
         turl="https://meridianuniversity.edu/academics/psychology/psyd-in-clinical-psychology",
         url="https://meridianuniversity.edu/academics/psychology/psyd-in-clinical-psychology",
         note="The only hybrid or online doctorate on this list, and the only one that sells a triple-licensure pathway — psychologist, MFT and LPCC from one degree. Note its own caveat: students entering with Advanced Standing do not meet the MFT or LPCC educational requirements. It publishes no internship match rate, EPPP pass rate or attrition data, which APA-accredited programs are required to disclose."),
    dict(inst="Pacifica Graduate Institute", city="Carpinteria and Santa Barbara",
         apa="none", apa_since=None, apa_next=None,
         degree="PsyD in Counseling Psychology with Emphasis in Depth Psychology",
         units="106 quarter units",
         length="4 years: three of curriculum including the dissertation, plus a year of internship",
         fmt="Low-residency, on-campus intensives",
         per_unit=None, total=None, tyear="2025-26",
         turl="https://www.pacifica.edu/financial-aid/cost-of-attendance/",
         url="https://www.pacifica.edu/degree-program/psy-d-counseling-psychology/",
         note="$32,600 a year. Pacifica states plainly that its doctoral programs in Counseling Psychology are not APA-accredited. Its separate PsyD in CLINICAL Psychology is not enrolling — its own 2025-26 catalog says “currently not enrolling students in this program. There are no cohorts in coursework.” Three easily-confused depth doctorates run here; check which one you are reading about."),
    dict(inst="Sofia University", city="Palo Alto",
         apa="none", apa_since=None, apa_next=None,
         degree="Doctor of Psychology (PsyD) in Clinical Psychology",
         units="120 units from a bachelor’s; 75 with 45 graduate transfer units",
         length="4–5 years", fmt="Campus-based, quarter calendar",
         per_unit=970, total=None, tyear="2025-26",
         turl="https://catalog.sofia.edu/tuition-and-fees",
         url="https://catalog.sofia.edu/clinical-psychology-doctoral/doctor-of-psychology/doctor-of-psychology-psyd-in-clinical-psychology",
         note="Appears dormant and its own materials contradict each other: the catalog page says “this program is not accepting any new students for 2022–23” while the 2025–26 tuition table still carries rates for it. Ask before applying. Sofia is WSCUC-accredited and in good standing — an earlier report of a Notice of Concern was wrong."),
]

# Programs that no longer exist, or exist only for students already in them.
GONE = [
    ("John F. Kennedy University", "Pleasant Hill",
     "Closed. The university's programs were absorbed into National University in 2021, and APA accreditation of the teach-out was withdrawn effective 30 September 2024. Students who finished under it graduated from an accredited program. The live successor is National University's own PsyD, separately accredited in March 2024."),
    ("Argosy University / American School of Professional Psychology", "several California campuses",
     "Closed in the 2019 collapse. Its California graduates still appear in the Board's licence counts years later, which is a fact about when people licensed, not evidence the school exists."),
    ("Antioch University Santa Barbara", "Santa Barbara",
     "Discontinued. It has sat on Antioch's own inactive-programs list since the 2022–23 catalog and is absent from the 2025–26 one. It was never APA-accredited — Antioch's accreditation page lists its Santa Barbara clinical PsyD as “no programmatic/specialized accreditation granted” while its New England and Seattle programs are accredited. Antioch is still billing continuing students, which is what a teach-out looks like."),
    ("The Chicago School, Irvine", "Irvine",
     "Relocated, not closed. The Irvine PsyD moved to Anaheim in spring 2021 and the Anaheim program is that program. There is no Chicago School PsyD in Irvine, and there never was one in San Diego."),
]

# Not regionally accredited. For anyone applying since 2020 this is decisive.
DEAD_END = [
    ("Ryokan College", "Los Angeles",
     "Still advertises a “Doctor of Psychology in Clinical Psychology (for licensure in California).” That claim reflects the rule before 2020."),
    ("Professional School of Psychology", "Sacramento", None),
    ("The Reiss-Davis Graduate Center", "Los Angeles", None),
    ("San Diego University for Integrative Studies", "San Diego", None),
]
